### PR TITLE
Added subset_sum [Striver Sheet]

### PR DESCRIPTION
**Pull request by manujgrover71**

### CODE REVIEW

**Comment by Ayon-SSP** [comment]
Nice Code, But you Have to create a Folder `Day 09` in that Name the file  `Subset_Sums.cpp` Add the Code
> Follow the Path
```css
The-SDE-Prep/4]_SDE Sheet's/Strivers SDE Sheet/C++
```

image

**Comment by Ayon-SSP** [comment]
@manujgrover71 Just now I Changed the Folders Structure Now It's easy to understand PR now.

**Comment by manujgrover71** [comment]
Cool, no worries.

**Comment by Ayon-SSP** [comment]
download

**Pull request merged**
