### PR TITLE
Added merge and quick sort in C

### PR DESCRIPTION
**Pull request by jordanhilado**

### CODE REVIEW

**Comment by Ayon-SSP** [comment]
**If you appreciate my work, please 🌟 this repository. It motivates me. 🚀🚀**

**Comment by Ayon-SSP** [comment]
# Make 2 different files 
* One For Merge Sort
* And one for quick sort

**Comment by jordanhilado** [comment]
done 👍

**Comment by Ayon-SSP** [comment]
**Happy coding please 🌟 this repository. It motivates me. 🚀**

**Pull request merged**
