### PR TITLE
Create knapsack_problem.cpp

### PR DESCRIPTION
**Pull request by shivamRamani**
* added knapsack algorithm in c++

### CODE REVIEW

**Comment by shivamRamani** [comment]
Please also add hacktoberfest lable

**Comment by Ayon-SSP** [comment]
If you appreciate my work, please 🌟 this repository. It motivates me. 🚀

**Review by SaicharanKandukuri — APPROVED** [review]

**Review by SaicharanKandukuri — CHANGES_REQUESTED** [review]
@shivamRamani you code has these issues
- include all appropriate headers
- missing `main()` ?
- no comments in code about its functionality

**Comment by shivamRamani** [comment]
I updated the knapsack_problem.cpp and solved all issues can u review it one more time

**Review by SaicharanKandukuri — APPROVED** [review]

**Review by SaicharanKandukuri — APPROVED** [review]

**Comment by SaicharanKandukuri** [comment]
Thanks for the contribution @shivamRamani 

> Enjoy HacktoberFest :purple_heart:

**Pull request merged**
